/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * Admin api endpoints
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AdminUserResponse,
  HTTPValidationError,
  UserChangePasswordRequest,
  UserCreateRequest,
  UserListParams,
  UserUpdateRequest,
  UsersListResponse,
} from "../../model";

import { customInstance } from "../../../lib/api-client";
import type { ErrorType, BodyType } from "../../../lib/api-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetCurrentAdminUserUrl = () => {
  return `/users/self`;
};

/**
 * @summary Get Current Admin User
 */
export const getCurrentAdminUser = async (
  options?: RequestInit
): Promise<AdminUserResponse> => {
  return customInstance<AdminUserResponse>(getGetCurrentAdminUserUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetCurrentAdminUserQueryKey = () => {
  return [`/users/self`] as const;
};

export const getGetCurrentAdminUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentAdminUser>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getCurrentAdminUser>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCurrentAdminUserQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCurrentAdminUser>>
  > = ({ signal }) => getCurrentAdminUser({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentAdminUser>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCurrentAdminUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentAdminUser>>
>;
export type GetCurrentAdminUserQueryError = ErrorType<unknown>;

export function useGetCurrentAdminUser<
  TData = Awaited<ReturnType<typeof getCurrentAdminUser>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCurrentAdminUser>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentAdminUser>>,
          TError,
          Awaited<ReturnType<typeof getCurrentAdminUser>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCurrentAdminUser<
  TData = Awaited<ReturnType<typeof getCurrentAdminUser>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCurrentAdminUser>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentAdminUser>>,
          TError,
          Awaited<ReturnType<typeof getCurrentAdminUser>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCurrentAdminUser<
  TData = Awaited<ReturnType<typeof getCurrentAdminUser>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCurrentAdminUser>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Current Admin User
 */

export function useGetCurrentAdminUser<
  TData = Awaited<ReturnType<typeof getCurrentAdminUser>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCurrentAdminUser>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCurrentAdminUserQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getUserListUrl = (params?: UserListParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/users?${stringifiedParams}`
    : `/users`;
};

/**
 * @summary User List
 */
export const userList = async (
  params?: UserListParams,
  options?: RequestInit
): Promise<UsersListResponse> => {
  return customInstance<UsersListResponse>(getUserListUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getUserListQueryKey = (params?: UserListParams) => {
  return [`/users`, ...(params ? [params] : [])] as const;
};

export const getUserListQueryOptions = <
  TData = Awaited<ReturnType<typeof userList>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params?: UserListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userList>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUserListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof userList>>> = ({
    signal,
  }) => userList(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof userList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UserListQueryResult = NonNullable<
  Awaited<ReturnType<typeof userList>>
>;
export type UserListQueryError = ErrorType<HTTPValidationError>;

export function useUserList<
  TData = Awaited<ReturnType<typeof userList>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: undefined | UserListParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userList>>,
          TError,
          Awaited<ReturnType<typeof userList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUserList<
  TData = Awaited<ReturnType<typeof userList>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params?: UserListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userList>>,
          TError,
          Awaited<ReturnType<typeof userList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUserList<
  TData = Awaited<ReturnType<typeof userList>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params?: UserListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userList>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary User List
 */

export function useUserList<
  TData = Awaited<ReturnType<typeof userList>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params?: UserListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userList>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getUserListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getUserCreateUrl = () => {
  return `/users`;
};

/**
 * @summary User Create
 */
export const userCreate = async (
  userCreateRequest: UserCreateRequest,
  options?: RequestInit
): Promise<AdminUserResponse> => {
  return customInstance<AdminUserResponse>(getUserCreateUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(userCreateRequest),
  });
};

export const getUserCreateMutationOptions = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userCreate>>,
    TError,
    { data: BodyType<UserCreateRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userCreate>>,
  TError,
  { data: BodyType<UserCreateRequest> },
  TContext
> => {
  const mutationKey = ["userCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userCreate>>,
    { data: BodyType<UserCreateRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return userCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof userCreate>>
>;
export type UserCreateMutationBody = BodyType<UserCreateRequest>;
export type UserCreateMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary User Create
 */
export const useUserCreate = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof userCreate>>,
      TError,
      { data: BodyType<UserCreateRequest> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof userCreate>>,
  TError,
  { data: BodyType<UserCreateRequest> },
  TContext
> => {
  return useMutation(getUserCreateMutationOptions(options), queryClient);
};
export const getUserUpdateUrl = (userId: string) => {
  return `/users/${userId}`;
};

/**
 * @summary User Update
 */
export const userUpdate = async (
  userId: string,
  userUpdateRequest: UserUpdateRequest,
  options?: RequestInit
): Promise<AdminUserResponse> => {
  return customInstance<AdminUserResponse>(getUserUpdateUrl(userId), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(userUpdateRequest),
  });
};

export const getUserUpdateMutationOptions = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userUpdate>>,
    TError,
    { userId: string; data: BodyType<UserUpdateRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userUpdate>>,
  TError,
  { userId: string; data: BodyType<UserUpdateRequest> },
  TContext
> => {
  const mutationKey = ["userUpdate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userUpdate>>,
    { userId: string; data: BodyType<UserUpdateRequest> }
  > = (props) => {
    const { userId, data } = props ?? {};

    return userUpdate(userId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof userUpdate>>
>;
export type UserUpdateMutationBody = BodyType<UserUpdateRequest>;
export type UserUpdateMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary User Update
 */
export const useUserUpdate = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof userUpdate>>,
      TError,
      { userId: string; data: BodyType<UserUpdateRequest> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof userUpdate>>,
  TError,
  { userId: string; data: BodyType<UserUpdateRequest> },
  TContext
> => {
  return useMutation(getUserUpdateMutationOptions(options), queryClient);
};
export const getUserDeleteUrl = (userId: string) => {
  return `/users/${userId}`;
};

/**
 * @summary User Delete
 */
export const userDelete = async (
  userId: string,
  options?: RequestInit
): Promise<void> => {
  return customInstance<void>(getUserDeleteUrl(userId), {
    ...options,
    method: "DELETE",
  });
};

export const getUserDeleteMutationOptions = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userDelete>>,
    TError,
    { userId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userDelete>>,
  TError,
  { userId: string },
  TContext
> => {
  const mutationKey = ["userDelete"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userDelete>>,
    { userId: string }
  > = (props) => {
    const { userId } = props ?? {};

    return userDelete(userId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof userDelete>>
>;

export type UserDeleteMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary User Delete
 */
export const useUserDelete = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof userDelete>>,
      TError,
      { userId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof userDelete>>,
  TError,
  { userId: string },
  TContext
> => {
  return useMutation(getUserDeleteMutationOptions(options), queryClient);
};
export const getUserChangePasswordUrl = (userId: string) => {
  return `/users/${userId}/change-password`;
};

/**
 * @summary User Change Password
 */
export const userChangePassword = async (
  userId: string,
  userChangePasswordRequest: UserChangePasswordRequest,
  options?: RequestInit
): Promise<void> => {
  return customInstance<void>(getUserChangePasswordUrl(userId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(userChangePasswordRequest),
  });
};

export const getUserChangePasswordMutationOptions = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userChangePassword>>,
    TError,
    { userId: string; data: BodyType<UserChangePasswordRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userChangePassword>>,
  TError,
  { userId: string; data: BodyType<UserChangePasswordRequest> },
  TContext
> => {
  const mutationKey = ["userChangePassword"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userChangePassword>>,
    { userId: string; data: BodyType<UserChangePasswordRequest> }
  > = (props) => {
    const { userId, data } = props ?? {};

    return userChangePassword(userId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserChangePasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof userChangePassword>>
>;
export type UserChangePasswordMutationBody =
  BodyType<UserChangePasswordRequest>;
export type UserChangePasswordMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary User Change Password
 */
export const useUserChangePassword = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof userChangePassword>>,
      TError,
      { userId: string; data: BodyType<UserChangePasswordRequest> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof userChangePassword>>,
  TError,
  { userId: string; data: BodyType<UserChangePasswordRequest> },
  TContext
> => {
  return useMutation(
    getUserChangePasswordMutationOptions(options),
    queryClient
  );
};
