/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * Platform api endpoints
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Health
 */
export const HealthResponse = zod.object({
  status: zod.string(),
});
