/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * Platform api endpoints
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Auth
 */
export const AuthBody = zod.object({
  email: zod.string().email(),
  password: zod.string(),
});

export const AuthResponse = zod.object({
  access_token: zod.string(),
});

/**
 * @summary Logout
 */
export const LogoutResponse = zod.object({
  message: zod.string(),
});
