/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * Internal api endpoints
 * OpenAPI spec version: 0.1.0
 */

export interface UserChangePasswordRequest {
  /** @minLength 8 */
  password: string;
}
