/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * Internal api endpoints
 * OpenAPI spec version: 0.1.0
 */
import type { InternalUserResponse } from "./internalUserResponse";

export interface UsersListResponse {
  items: InternalUserResponse[];
  total: number;
  limit: number;
  offset: number;
}
