/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * Admin api endpoints
 * OpenAPI spec version: 0.1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  AuthRequest,
  AuthResponse,
  HTTPValidationError,
  MessageResponse,
} from "../../model";

import { customInstance } from "../../../lib/api-client";
import type { ErrorType, BodyType } from "../../../lib/api-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getAuthUrl = () => {
  return `/auth`;
};

/**
 * @summary Auth
 */
export const auth = async (
  authRequest: AuthRequest,
  options?: RequestInit
): Promise<AuthResponse> => {
  return customInstance<AuthResponse>(getAuthUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(authRequest),
  });
};

export const getAuthMutationOptions = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof auth>>,
    TError,
    { data: BodyType<AuthRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof auth>>,
  TError,
  { data: BodyType<AuthRequest> },
  TContext
> => {
  const mutationKey = ["auth"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof auth>>,
    { data: BodyType<AuthRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return auth(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthMutationResult = NonNullable<Awaited<ReturnType<typeof auth>>>;
export type AuthMutationBody = BodyType<AuthRequest>;
export type AuthMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Auth
 */
export const useAuth = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof auth>>,
      TError,
      { data: BodyType<AuthRequest> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof auth>>,
  TError,
  { data: BodyType<AuthRequest> },
  TContext
> => {
  return useMutation(getAuthMutationOptions(options), queryClient);
};
export const getLogoutUrl = () => {
  return `/logout`;
};

/**
 * @summary Logout
 */
export const logout = async (
  options?: RequestInit
): Promise<MessageResponse> => {
  return customInstance<MessageResponse>(getLogoutUrl(), {
    ...options,
    method: "POST",
  });
};

export const getLogoutMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logout>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof logout>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["logout"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof logout>>,
    void
  > = () => {
    return logout(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof logout>>
>;

export type LogoutMutationError = ErrorType<unknown>;

/**
 * @summary Logout
 */
export const useLogout = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof logout>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof logout>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getLogoutMutationOptions(options), queryClient);
};
