/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * Admin api endpoints
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Get Current Admin User
 */
export const GetCurrentAdminUserResponse = zod.object({
  id: zod.string(),
  created_at: zod.string().datetime({ offset: true }),
  updated_at: zod.union([zod.string().datetime({ offset: true }), zod.null()]),
  first_name: zod.string(),
  last_name: zod.string(),
  email: zod.string(),
  is_admin: zod.boolean(),
  is_active: zod.boolean(),
});

/**
 * @summary User List
 */
export const userListQueryLimitDefault = 50;
export const userListQueryLimitMax = 100;

export const userListQueryOffsetDefault = 0;
export const userListQueryOffsetMin = 0;

export const UserListQueryParams = zod.object({
  limit: zod
    .number()
    .min(1)
    .max(userListQueryLimitMax)
    .default(userListQueryLimitDefault),
  offset: zod
    .number()
    .min(userListQueryOffsetMin)
    .default(userListQueryOffsetDefault),
});

export const UserListResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string(),
      created_at: zod.string().datetime({ offset: true }),
      updated_at: zod.union([
        zod.string().datetime({ offset: true }),
        zod.null(),
      ]),
      first_name: zod.string(),
      last_name: zod.string(),
      email: zod.string(),
      is_admin: zod.boolean(),
      is_active: zod.boolean(),
    })
  ),
  total: zod.number(),
  limit: zod.number(),
  offset: zod.number(),
});

/**
 * @summary User Create
 */
export const userCreateBodyFirstNameMax = 100;

export const userCreateBodyLastNameMax = 100;

export const userCreateBodyPasswordMin = 8;

export const userCreateBodyIsAdminDefault = false;
export const userCreateBodyIsActiveDefault = true;

export const UserCreateBody = zod.object({
  first_name: zod.string().min(1).max(userCreateBodyFirstNameMax),
  last_name: zod.string().min(1).max(userCreateBodyLastNameMax),
  email: zod.string().email(),
  password: zod.string().min(userCreateBodyPasswordMin),
  is_admin: zod.boolean().default(userCreateBodyIsAdminDefault),
  is_active: zod.boolean().default(userCreateBodyIsActiveDefault),
});

export const UserCreateResponse = zod.object({
  id: zod.string(),
  created_at: zod.string().datetime({ offset: true }),
  updated_at: zod.union([zod.string().datetime({ offset: true }), zod.null()]),
  first_name: zod.string(),
  last_name: zod.string(),
  email: zod.string(),
  is_admin: zod.boolean(),
  is_active: zod.boolean(),
});

/**
 * @summary User Update
 */
export const UserUpdateParams = zod.object({
  user_id: zod.string().uuid(),
});

export const userUpdateBodyFirstNameOneMax = 100;

export const userUpdateBodyLastNameOneMax = 100;

export const UserUpdateBody = zod.object({
  first_name: zod
    .union([zod.string().min(1).max(userUpdateBodyFirstNameOneMax), zod.null()])
    .optional(),
  last_name: zod
    .union([zod.string().min(1).max(userUpdateBodyLastNameOneMax), zod.null()])
    .optional(),
  email: zod.union([zod.string().email(), zod.null()]).optional(),
  is_admin: zod.union([zod.boolean(), zod.null()]).optional(),
  is_active: zod.union([zod.boolean(), zod.null()]).optional(),
});

export const UserUpdateResponse = zod.object({
  id: zod.string(),
  created_at: zod.string().datetime({ offset: true }),
  updated_at: zod.union([zod.string().datetime({ offset: true }), zod.null()]),
  first_name: zod.string(),
  last_name: zod.string(),
  email: zod.string(),
  is_admin: zod.boolean(),
  is_active: zod.boolean(),
});

/**
 * @summary User Delete
 */
export const UserDeleteParams = zod.object({
  user_id: zod.string().uuid(),
});

export const UserDeleteResponse = zod.void();

/**
 * @summary User Change Password
 */
export const UserChangePasswordParams = zod.object({
  user_id: zod.string().uuid(),
});

export const userChangePasswordBodyPasswordMin = 8;

export const UserChangePasswordBody = zod.object({
  password: zod.string().min(userChangePasswordBodyPasswordMin),
});

export const UserChangePasswordResponse = zod.void();
