"""add is_admin to users

Revision ID: c75a420ef405
Revises: 70955f4a9d1e
Create Date: 2026-07-17 22:01:18.533860

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c75a420ef405"
down_revision: Union[str, None] = "70955f4a9d1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_admin",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # Backfill applied via server_default above; drop it so future inserts rely
    # on the application/model default instead of a DB-level constant.
    op.alter_column("users", "is_admin", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###
