/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * Admin api endpoints
 * OpenAPI spec version: 0.1.0
 */

export interface UserCreateRequest {
  /**
   * @minLength 1
   * @maxLength 100
   */
  first_name: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  last_name: string;
  email: string;
  /** @minLength 8 */
  password: string;
  is_admin?: boolean;
  is_active?: boolean;
}
