/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * Admin api endpoints
 * OpenAPI spec version: 0.1.0
 */

export type UserListParams = {
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * @minimum 0
   */
  offset?: number;
};
