/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * Admin api endpoints
 * OpenAPI spec version: 0.1.0
 */

export interface UserUpdateRequest {
  first_name?: string | null;
  last_name?: string | null;
  email?: string | null;
  is_admin?: boolean | null;
  is_active?: boolean | null;
}
