/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * Admin api endpoints
 * OpenAPI spec version: 0.1.0
 */
import type { AdminUserResponse } from "./adminUserResponse";

export interface UsersListResponse {
  items: AdminUserResponse[];
  total: number;
  limit: number;
  offset: number;
}
