/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * FastAPI
 * Platform api endpoints
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Get Current User
 */
export const GetCurrentUserResponse = zod.object({
  id: zod.string(),
  created_at: zod.string().datetime({ offset: true }),
  updated_at: zod.union([zod.string().datetime({ offset: true }), zod.null()]),
  first_name: zod.string(),
  last_name: zod.string(),
  email: zod.string(),
});
